### ISSUE TITLE
Error, npm install failed

### ISSUE THREAD

**Issue by emharsha1812** [arlbibek/dVoting#3]
I cloned the repository and inside the client folder, I ran npm install
However it gave a series of errors, I tried multiple times but everytime it would give me the same error

Heres the list of all the errors

npm ERR! code 1
npm ERR! path F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR!   bufferutil.cc
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(34): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(6802): note: see declaration of 'v8::FunctionTemplate::GetFunction'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(34): error C2661: 'Nan::Set': no overloaded function takes 2 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(50): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(57): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]   
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(68): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(70): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(89): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(90): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(92): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]     
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(93): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]   
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3107): note: see declaration of 'v8::Value::Int32Value'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\bufferutil.cc(94): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\bufferutil.vcxproj]   
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3107): note: see declaration of 'v8::Value::Int32Value'
npm ERR!   validation.cc
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\validation.cc(114): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\validation.vcxproj]
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(6802): note: see declaration of 'v8::FunctionTemplate::GetFunction'
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\validation.cc(114): error C2661: 'Nan::Set': no overloaded function takes 2 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\validation.vcxproj]
npm ERR! f:\voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\src\validation.cc(133): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocket\build\validation.vcxproj]    
npm ERR!   c:\users\harsh\appdata\local\node-gyp\cache\16.13.2\include\node\v8.h(3060): note: see declaration of 'v8::Value::ToObject'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "C:\msys64\mingw64\bin\python3.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1525) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:13036) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\msys64\mingw64\bin\python3.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\harsh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'F:\\Voting blockchain cloned repos\\client\\node_modules\\web3-providers-ws\\node_modules\\websocket\\build\\config.gypi',        
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\harsh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\harsh\\AppData\\Local\\node-gyp\\Cache\\16.13.2\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\harsh\\AppData\\Local\\node-gyp\\Cache\\16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\harsh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\harsh\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.2\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=F:\\Voting blockchain cloned repos\\client\\node_modules\\web3-providers-ws\\node_modules\\websocket',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'F:\\Voting blockchain cloned repos\\client\\node_modules\\web3-providers-ws\\node_modules\\websocket\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\harsh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\harsh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd F:\Voting blockchain cloned repos\client\node_modules\web3-providers-ws\node_modules\websocketnpm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v7.1.2npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\harsh\AppData\Local\npm-cache\_logs\2022-02-09T06_07_45_025Z-debug.log

P.S:- I thought it was because there were both yarn and npm json files in the client folder. I deleted the yarn one and try to run npm install again, but the error kept peprsisting. Please Help

**Comment by arlbibek** [comment]
What version of the node are you running? Try changing the version and it may work.

**Comment by emharsha1812** [comment]
I deleted the package.lock JSON file and then ran npm install and it started working. Thanks!
 
I also have one other question, was there a specific reason as to why you used class-based approach in writing the react code rather than the functional-based approach which is widely incorporated?

**Comment by arlbibek** [comment]
> I deleted the package.lock JSON file and then ran npm install and it started working. Thanks!

Cheers! Thanks for sharing. 

> I also have one other question, was there a specific reason as to why you used class-based approach in writing the react code rather than the functional-based approach which is widely incorporated?

Good question, I used the class-based approach simply because it seem right and easy for me to implement at the time (also a lot of external resources that I referenced for the project were such), that is the major reason. 
Currently, I'm trying to rebuild the project using [Next.js](https://nextjs.org/) whilst implementing the functional approach, but sadly I've very little time and knowledge to do so.
