### ISSUE TITLE
Admin Catalogue

### ISSUE THREAD

**Issue by vidixha** [arlbibek/dVoting#6]
"Admin might not approve your account if the provided Phone number nub does not matches the account address registered in admins catalogue."
Can you please share what is the admins catalogue? I am not able to register user

**Comment by arlbibek** [comment]
Currently, we do not have any verification methods for verifying registered users and the concept is that **the admin will have some sort of list (i.e catalogue) with the details of all the people that are to take part in the election**. The mentioned list could be a CSV file, spreadsheets or a hard copy ledger.

**Comment by vidixha** [comment]
Ok, and can u please tell what is the database you are using?

**Comment by arlbibek** [comment]
There's isn't a "database" for the app, **all the data are stored in the blockchain** (see [here](https://youtu.be/SSo_EIwHSd4 "How does a blockchain work - Simply Explained")). This is the whole point of the app, not to store data in a centralized database.
