### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by IsaacPrime** [arlbibek/dVoting#8]
Failed to compile.

./src/component/Admin/AddCandidate/AddCandidate.js
Module not found: Can't resolve '../../../contracts/Election.json' 
in 'C:\Users\I S A A C\Downloads\dVoting\client\src\component\Admin\AddCandidate'

**Comment by arlbibek** [comment]
Is the issue still persistent? If yes, can you put all of the console output, so that it's easy to figure out what went wrong?

**Comment by arrabisPiolo** [comment]
Check the spelling of the module name: Make sure you have spelled the module name correctly and that it matches the name of the module in the file system.
or 
Check the file path: Double-check the file path of the module you are importing. Ensure that the file path is correct and the module is in the right directory.

**Comment by IsaacPrime** [comment]
I've tried the approach as stated and here is the complete console log output
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle client@0.1.0~prestart: client@0.1.0
6 info lifecycle client@0.1.0~start: client@0.1.0
7 verbose lifecycle client@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\I S A A C\OneDrive\Desktop\dVoting\client\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Users\I S A A C\AppData\Local\Microsoft\WindowsApps;C:\Users\I S A A C\AppData\Roaming\npm;C:\Users\I S A A C\AppData\Roaming\Composer\vendor\bin;C:\Users\I S A A C\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle client@0.1.0~start: CWD: C:\Users\I S A A C\OneDrive\Desktop\dVoting\client
10 silly lifecycle client@0.1.0~start: Args: [ '/d /s /c', 'react-scripts --openssl-legacy-provider start' ]
11 silly lifecycle client@0.1.0~start: Returned: code: 9  signal: null
12 info lifecycle client@0.1.0~start: Failed to exec start script
13 verbose stack Error: client@0.1.0 start: `react-scripts --openssl-legacy-provider start`
13 verbose stack Exit status 9
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid client@0.1.0
15 verbose cwd C:\Users\I S A A C\OneDrive\Desktop\dVoting\client
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 9
22 error client@0.1.0 start: `react-scripts --openssl-legacy-provider start`
22 error Exit status 9
23 error Failed at the client@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 9, true ]`

**Comment by IsaacPrime** [comment]
In which file does the contact address go into

**Comment by IsaacPrime** [comment]
Finally, It's working fine. thankyou
